name: Publish PyPI package
on: push
# on:
#   release:
#     types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install the development and release requirements
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine
        pip install -r requirements.pip
    - name: Cleanup build and dist folders
      run: rm -rf build dist pyxform.egg-info
    - name: Prepare sdist and bdist_wheel distributions
      run: python setup.py sdist bdist_wheel
    # - name: Publish release to PyPI with twine
    #   run: twine upload dist/pyxform-*-py2.py3-none-any.whl dist/pyxform-*.tar.gz
    #   env:
    #     TWINE_USERNAME: __token__
    #     TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
